# config/packages/security.yaml

security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        admin_provider:
            id: App\Security\AdminProvider

    firewalls:
        dev:
            pattern: ^/(admin|other_path)
            security: false
        main:
            form_login:
                login_path: admin_login
                check_path: admin_login
                default_target_path: app_home
                use_referer: true
            logout:
                path: admin_logout
                target: app_home

    
            
            

    access_control:
        - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }

    # ... (other configuration)

 